name: asset-vulnerability-scanner

services:
  api:
    build:
      context: docker/php
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      - ./.:/var/www/html
    environment:
      DB_HOST: db
      DB_USERNAME: dev
      DB_PASSWORD: dev
      PHP_IDE_CONFIG: "serverName=swoole"
      XDEBUG_SESSION: "PHPSTORM"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_USERNAME: dev
      CLICKHOUSE_PASSWORD: dev
    labels:
      com.datadoghq.ad.logs: '[{"source": "php", "service": "asset-vulnerability-api"}]'
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    environment:
      CLICKHOUSE_USER: dev
      CLICKHOUSE_PASSWORD: dev
      CLICKHOUSE_DEFAULT_USER: root
      CLICKHOUSE_DEFAULT_PASSWORD: root
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml

  redis:
    image: redis:8.2.3-alpine
    restart: always
    ports:
      - "6379:6379"

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    hostname: dd-agent
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE}
      DD_HOSTNAME: dd-agent-local
      DD_ENV: "dev"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_PROFILING_ENABLED: "auto"
      DD_IAST_ENABLED: "true"
      DD_APPSEC_SCA_ENABLED: "true"
      DD_LOGS_ENABLED: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_APM_RECEIVER_SOCKET: "/var/run/datadog/apm.socket"
      DD_DOGSTATSD_SOCKET: "/var/run/datadog/dsd.socket"
      DD_DOGSTATSD_METRICS_STATS_ENABLE: "true"
      DD_DOGSTATSD_TCP_ENABLED: "true"
    ports:
      - "8126:8126/udp"
      - "8125:8125/udp"
    volumes:
      - /var/run/datadog:/var/run/datadog
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

volumes:
  postgres-data:
  clickhouse-data:
  clickhouse-logs:
