services:
  api:
    build:
      context: ./php
      dockerfile: Dockerfile
    user: "1000:1000"
    volumes:
      - ../.:/var/www/html
    environment:
      DB_HOST: db
      DB_USERNAME: dev
      DB_PASSWORD: dev
      PHP_IDE_CONFIG: "serverName=swoole"
      XDEBUG_SESSION: "PHPSTORM"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_USERNAME: dev
      CLICKHOUSE_PASSWORD: dev
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - asset-vulnerability-scanner-network
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - asset-vulnerability-scanner-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - asset-vulnerability-scanner-network

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    environment:
      CLICKHOUSE_USER: dev
      CLICKHOUSE_PASSWORD: dev
      CLICKHOUSE_DEFAULT_USER: root
      CLICKHOUSE_DEFAULT_PASSWORD: root
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
    networks:
      - asset-vulnerability-scanner-network

networks:
  asset-vulnerability-scanner-network:
    driver: bridge

volumes:
  postgres-data:
  clickhouse-data:
  clickhouse-logs:
